export default {
  "login": "codeavak",
  "id": 29570845,
  "node_id": "MDQ6VXNlcjI5NTcwODQ1",
  "avatar_url": "https://avatars2.githubusercontent.com/u/29570845?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/codeavak",
  "html_url": "https://github.com/codeavak",
  "followers_url": "https://api.github.com/users/codeavak/followers",
  "following_url": "https://api.github.com/users/codeavak/following{/other_user}",
  "gists_url": "https://api.github.com/users/codeavak/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/codeavak/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/codeavak/subscriptions",
  "organizations_url": "https://api.github.com/users/codeavak/orgs",
  "repos_url": "https://api.github.com/users/codeavak/repos",
  "events_url": "https://api.github.com/users/codeavak/events{/privacy}",
  "received_events_url": "https://api.github.com/users/codeavak/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Varoojan Avakian",
  "company": "Oakwood School",
  "blog": "https://codeavak.com/",
  "location": "Los Angeles, California",
  "email": null,
  "hireable": null,
  "bio": "I love collaborating with people and building useful tools and hopefully learning something new along the way! ",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 1,
  "followers": 3,
  "following": 3,
  "created_at": "2017-06-20T10:54:19Z",
  "updated_at": "2021-01-04T06:51:25Z"
  };