export default [
  {
  "login": "charalson72777",
  "id": 30251683,
  "node_id": "MDQ6VXNlcjMwMjUxNjgz",
  "avatar_url": "https://avatars3.githubusercontent.com/u/30251683?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/charalson72777",
  "html_url": "https://github.com/charalson72777",
  "followers_url": "https://api.github.com/users/charalson72777/followers",
  "following_url": "https://api.github.com/users/charalson72777/following{/other_user}",
  "gists_url": "https://api.github.com/users/charalson72777/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/charalson72777/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/charalson72777/subscriptions",
  "organizations_url": "https://api.github.com/users/charalson72777/orgs",
  "repos_url": "https://api.github.com/users/charalson72777/repos",
  "events_url": "https://api.github.com/users/charalson72777/events{/privacy}",
  "received_events_url": "https://api.github.com/users/charalson72777/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "JosephNiccoli",
  "id": 30275962,
  "node_id": "MDQ6VXNlcjMwMjc1OTYy",
  "avatar_url": "https://avatars2.githubusercontent.com/u/30275962?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JosephNiccoli",
  "html_url": "https://github.com/JosephNiccoli",
  "followers_url": "https://api.github.com/users/JosephNiccoli/followers",
  "following_url": "https://api.github.com/users/JosephNiccoli/following{/other_user}",
  "gists_url": "https://api.github.com/users/JosephNiccoli/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JosephNiccoli/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JosephNiccoli/subscriptions",
  "organizations_url": "https://api.github.com/users/JosephNiccoli/orgs",
  "repos_url": "https://api.github.com/users/JosephNiccoli/repos",
  "events_url": "https://api.github.com/users/JosephNiccoli/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JosephNiccoli/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "Ralph-Fonz",
  "id": 12758537,
  "node_id": "MDQ6VXNlcjEyNzU4NTM3",
  "avatar_url": "https://avatars0.githubusercontent.com/u/12758537?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Ralph-Fonz",
  "html_url": "https://github.com/Ralph-Fonz",
  "followers_url": "https://api.github.com/users/Ralph-Fonz/followers",
  "following_url": "https://api.github.com/users/Ralph-Fonz/following{/other_user}",
  "gists_url": "https://api.github.com/users/Ralph-Fonz/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Ralph-Fonz/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Ralph-Fonz/subscriptions",
  "organizations_url": "https://api.github.com/users/Ralph-Fonz/orgs",
  "repos_url": "https://api.github.com/users/Ralph-Fonz/repos",
  "events_url": "https://api.github.com/users/Ralph-Fonz/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Ralph-Fonz/received_events",
  "type": "User",
  "site_admin": false
  }
  ];